export default {
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_FULFILLED: "GET_PRODUCTS_FULFILLED",
    FILTER_PRODUCT_BY_CATAGORY: "FILTER_PRODUCT_BY_CATAGORY",
    FILTER_PRODUCT_BY_PRICE: "FILTER_PRODUCT_BY_PRICE",
    FILTER_PRODUCT_BY_COLOR: "FILTER_PRODUCT_BY_COLOR",
    FILTER_PRODUCT_BY_TAG: "FILTER_PROUDCT_BY TAG",
    PRODUCT_SORT: "PRODUCT_SORT",
    FILTER_TOGGLER: "FILTER_TOGGLER",
    ORDER_PRODUCT: "ORDER_PRODUCT",
    ORDER_PRODUCTS: "ORDER_PRODUCTS",
    ORDER_PRODUCT_REMOVE: "ORDER_PRODUCT_REMOVE",
    ORDER_PRODUCT_MODAL: "ORDER_PRODUCT_MODAL",
}