export default {
   GET_LOGGEDIN: "GET_LOGGEDIN",
   GET_LOGGEDIN_FULFILLED: "GET_LOGGEDIN_FULFILLED",
   CREATE_USER: "CREATE_USER",
   LOG_OUT_USER: "LOG_OUT_USER",
   LOG_OUT_USER_FULFILLED: "LOG_OUT_USER_FULFILLED"
}